site_name: Camila Simsiroglu

# En producción (GitHub Pages) debe ser la URL real, ej: https://TU_USUARIO.github.io/my-hub/
site_url: ''

nav:
  - Home: index.md
  - Archive: archive.md
  - About: About-me.md
  - Blender Content:
      - Getting Started: Blender Content/Getting-Started.md
      - Modes in Blender: Blender Content/Modes-in-Blender copy.md
      - Modifiers: Blender Content/Modifiers.md
  - 3D Example: threejs-example.md
  - Documentation: documentation.md  # landing de Documentation (oculto en sidebar)

theme:
  name: material
  custom_dir: overrides
  
  features:
    - navigation.sections
    - navigation.expand
    - toc.integrate  # QUITÁ esta línea si la tenés

  palette:
    scheme: default
    primary: white
    accent: teal

  font:
    text: DM Sans
    code: JetBrains Mono

  logo: images/logo.png
  favicon: images/logo.ico

  features:
    - navigation.sections
    - navigation.expand

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite

extra_css:
  - css/custom.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js
  - js/3d-viewer.js

plugins:
  - search

extra:
  generator: false

copyright: ""
